name: "spec"

on: [push, pull_request]

jobs:
  # this runs the tests in the docker image against live postgres & mysql
  # and openresty
  docker:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    # - uses: leafo/lapis@master

    - name: build
      run: |
        docker build -t lapis-test .

    - name: test
      run: |
        docker run lapis-test


  # this runs all generic lua tests
  test:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit", "luajit-openresty"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@ef9239997afff6d2d8b42ec9729c1d4b7f2f1302
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5

    - name: build
      run: |
        [[ "${{ matrix.luaVersion }}" =~ ^5\.[12]$ ]] && luarocks install luabitop || true
        luarocks install busted
        luarocks install moonscript
        luarocks install tableshape
        luarocks install lsqlite3
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal -v
